merge im2deep into timsrescore branch
compomics/ms2rescore pull request #121
Opened 2024-02-13 12:02 UTC by ArthurDeclercq

2024-02-13 15:56 UTC, paretje requested changes

2024-02-13 15:56 UTC, paretje commented on ms2rescore/gui/app.py
> +        """IonMob configuration frame."""
```suggestion
        """im2deep configuration frame."""
```

2024-02-13 15:56 UTC, paretje commented on ms2rescore/parse_spectra.py
> -
I'm not sure about the name of this method, `get_missing_values`, given that it doesn't return missing values, but actually fills them with data from the mgf or mzml.

2024-02-13 15:56 UTC, paretje commented on ms2rescore/report/generate.py
> +        # TODO: the axis titles are gonna be retention time based so need to make them changeable in deeplc.plot
Should this be resolved in DeepLC before merging this?

2024-02-13 15:56 UTC, paretje commented on ms2rescore/feature_generators/im2deep.py
> +        """Placeholder"""  # TODO
Reminder ;)

2024-02-13 15:56 UTC, paretje commented on ms2rescore/feature_generators/im2deep.py
> +    # TODO: Make threshold a parameter
```suggestion
```
Or do you mean expose it as I see `add_features` doesn't have the parameter.

2024-02-18 09:56 UTC, RalfG commented on docs/source/config_schema.md
> +      - *null*
Duplicate?

2024-02-18 10:01 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +
todo

2024-02-18 10:03 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +        """
chore: replace with numpydoc style for correct parsing in Sphinx docs (https://numpydoc.readthedocs.io/en/latest/format.html)

2024-02-18 10:07 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +        Convert ion mobility to CCS.  #TODO: Took this from ionmob. how to reference?
You can write something like `Adapted from theGreatHerrLebert/ionmob (https://doi.org/10.1093/bioinformatics/btad486)` in the `Notes` section of the docstring.

2024-02-18 10:10 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +        return cal_psm_df
note: We should consider not using dataframes here (for a future PR).

2024-02-21 10:52 UTC, RalfG requested changes

2024-02-21 10:52 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +`github.com/compomics/deeplc <https://github.com/compomics/IM2Deep>`_ for more information.
Todo: Replace DeepLC with im2deep

2024-02-21 10:53 UTC, RalfG commented on ms2rescore/feature_generators/im2deep.py
> +`github.com/compomics/deeplc <https://github.com/compomics/IM2Deep>`_ for more information.
```suggestion
`github.com/compomics/IM2Deep <https://github.com/compomics/IM2Deep>`_ for more information.
```

2024-02-21 10:54 UTC, RalfG approved these changes

2024-02-21 10:58 UTC, merged