Streamlit webserver
compomics/ms2rescore pull request #32
Opened 2021-03-30 19:46 UTC by RalfG

Add code and Dockerfile for a minimal Streamlit webserver. User can upload data, set configuration options, and download zipped results. Basic plots showing the results are still missing, but should be feasible to implement in the near future. 

On each GitHub release, a docker image is built and pushed to ghcr.io.

2021-04-02 14:49 UTC, paretje requested changes

2021-04-02 14:49 UTC, paretje commented on streamlit/Dockerfile
> +COPY . .
If you use a relative destination, you should declare `WORKDIR`

2021-04-02 14:49 UTC, paretje commented on streamlit/ms2rescore_streamlit.py
> +        shutil.rmtree(tmp_dir.name)
You should use `tmp_dir.cleanup()` instead. Or use `tempfile.TemporaryDirectory` as a context manager.

2021-04-02 14:49 UTC, paretje commented on streamlit/streamlit_utils.py
> +        tmp.write(bytesio.getbuffer())
It's probably better to use `shutil.copyfileobj`.

2023-09-13 11:25 UTC, RalfG commented
Closing in favor of local desktop GUI

2023-09-13 11:25 UTC, closed without merging