Feature/feature sets
compomics/ms2rescore pull request #34
Opened 2021-08-10 09:55 UTC by ArthurDeclercq

- Replaced current feature sets with a list of lists with each list containing the features included in one pin file for rescoring
- Rewrote plotting.py with classes 
- added the option of plotting some rescore plots for all feature sets to see the influence of rescoring with different feature sets
- adjusted the readme with new feature sets options

2021-08-10 11:42 UTC, RalfG commented on ms2rescore/maxquant.py
> +        elif "Mass error [ppm]" in self._obj.columns:
Problem here is both exist. We need to allow both versions (and potentially also deal with this downstream?)

2021-08-10 12:08 UTC, RalfG requested changes

2021-08-10 12:08 UTC, RalfG commented on README.md
> +  - **Items** *(string)*: Must be one or a combination of:
Type of items should also be an array (`feature_sets` is an array of arrays of strings)

2021-08-10 12:08 UTC, RalfG commented on ms2rescore/__init__.py
> +                + "_features.pin",
Code clarity would improve if this string would be constructed beforehand. Idem below for pout

2021-08-10 12:08 UTC, RalfG commented on ms2rescore/__init__.py
> +            plotting._REREC.save_plots_to_pfd(
to pdf instead of `pfd`?

2021-08-12 12:52 UTC, RalfG requested changes
To do:
- [x] Update `configuration.md`
- [x] Get score name from upstream code? --> Yes: Use PEPREC file instead of PIN, always has `psm_score` column (for retention time).

2021-08-17 09:44 UTC, paretje requested changes
I wouldn't have used inheritance of an abstract class, but rather composition, but that can still easily be changed later on if necessary.

2021-08-17 09:44 UTC, paretje commented on ms2rescore/plotting.py
> +        ]
```suggestion
        plot_list =[
            list(self.df[self.df[decoy_label]][score_label]),
            list(self.df[~self.df[decoy_label]][score_label]),
        ]
```

2021-08-18 08:54 UTC, RalfG approved these changes

2021-08-18 08:55 UTC, merged